name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/webapp

      - name: Create an EC2
        uses: flyweightrocks/aws-ec2-action@v1
        with:
          instance-id: i-069a0d98304f25c79
          aws_default_region: us-east-1
          wait-instance-running: true
          

      - name: Deploy app to EC2
        uses: bitovi/github-actions-deploy-docker-to-ec2@v1.0.1
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          checkout: true
          aws_ec2_instance_create: true
          aws_ec2_ami_id: ami-0866a3c8686eaeeba
          aws_ec2_instance_type: t2-micro
          aws_ec2_security_group_name: launch-wizard-1
        

